"use strict";

// Authored expansion data. World services consume this catalog; no model writes it.
const C = require('./content');
const { ITEMS, STORY_NODES, ENEMIES, ENCOUNTERS, CLUES, CAMPAIGN } = C;
const { deepClone } = require('./rules');

Object.assign(CAMPAIGN,{
  title:'Briarwatch: Roads Beyond the Bell',
  subtitle:'A story-first d20 journey • towns, companions and the first advancement',
  levelRange:'1–10',
  premise:'A silenced ward-bell draws your party to Briarwatch. What you uncover will lead beyond the forest, through trading towns and fractured alliances, to the source of a region-wide collapse of the wards.'
});
// Correct descriptions before adding more systems. Charges are per physical kit.
ITEMS['healing-potion'].value=15;
ITEMS.antitoxin.value=12;
ITEMS.antitoxin.purpose='Action: cure Poisoned, or prepare advantage on the next poison saving throw. The protection is consumed by that save, not by unrelated saves.';
ITEMS['healers-kit'].value=12;
ITEMS['healers-kit'].purpose='Three uses per kit. Outside combat each use heals 1d6+2 HP. In combat it only stabilizes an unconscious, unstable ally (0 HP); it does not revive them.';
ITEMS['thornward-cloak'].purpose='Equip for +1 AC and advantage on your first Survival check after each long rest. This charge is shown on the character sheet.';
ITEMS['smoke-bomb'].value=18;
ITEMS['holy-water'].value=15;
const newItems = [
  {id:'greater-healing',name:'Greater Healing Draught',category:'consumable',rarity:'Uncommon',value:38,description:'A concentrated field remedy with a copper seal.',purpose:'Action: heal 4d4+4 HP in or out of combat.',usable:{contexts:['story','combat'],effect:'heal',formula:'4d4+4',target:'ally',cost:'action'}},
  {id:'climbing-kit',name:'Climbing Kit',category:'tool',rarity:'Common',value:24,description:'Pitons, harness and tested anchors, packed to be used rather than collected.',purpose:'Reusable: grants advantage on climbing routes that name this tool. At level 6, Fieldcraft also adds +2 to those checks.'},
  {id:'storm-grounder',name:'Storm Grounder',category:'tool',rarity:'Uncommon',value:32,description:'A braid of copper with ceramic handholds.',purpose:'Reusable: opens protected approaches to charged ward machinery and grants advantage on the named storm checks.'},
  {id:'lantern',name:'Shuttered Lantern',category:'tool',rarity:'Common',value:12,description:'A hooded lamp with a long-burning wick.',purpose:'Reusable: helps investigation in mines and drowned ruins when shown on a route card. Routine fuel tracking is deliberately omitted.'},
  {id:'herb-bundle',name:'Medicinal Herbs',category:'material',rarity:'Common',value:8,description:'Dried marshleaf wrapped against damp.',purpose:'Workshop ingredient: two bundles and 8 gold make one Greater Healing Draught. May also be sold.'},
  {id:'ward-fragment',name:'Ward Crystal Fragment',category:'material',rarity:'Uncommon',value:25,description:'A stable splinter recovered from a damaged ward.',purpose:'Workshop ingredient: one fragment and 30 gold make a Sentinel Charm. No quest requires this material, so crafting or selling is safe.'},
  {id:'sentinel-charm',name:'Sentinel Charm',category:'accessory',slot:'accessory',rarity:'Uncommon',value:70,description:'A small ward which firms the wearer’s resolve.',purpose:'Equip: +1 to every saving throw; useful for poison and magical hazards.',saveBonuses:{str:1,dex:1,con:1,int:1,wis:1,cha:1}},
  {id:'wayfarer-boots',name:'Wayfarer’s Boots',category:'accessory',slot:'accessory',rarity:'Uncommon',value:45,description:'Boots stitched for sure footing, not speed.',purpose:'Equip in the accessory slot: +2 Athletics and Survival. Replaces any other accessory.',skillBonuses:{athletics:2,survival:2}},
  {id:'dueling-blade',name:'Dueling Blade',category:'weapon',slot:'mainHand',rarity:'Uncommon',value:65,description:'A narrow, carefully weighted sword.',purpose:'Finesse, 1d8 piercing, +1 to hit. A precision alternative to heavier weapons.',weapon:{damage:'1d8',damageType:'piercing',ability:'finesse',properties:['finesse']},attackBonus:1},
  {id:'greatsword',name:'Roadwarden Greatsword',category:'weapon',slot:'mainHand',rarity:'Uncommon',value:65,description:'A two-handed blade that makes defending a doorway a commitment.',purpose:'Strength, 2d6 slashing. Two-handed: equipping removes your shield, trading defense for damage.',weapon:{damage:'2d6',damageType:'slashing',ability:'str',properties:['twoHanded']}},
  {id:'warbow',name:'Frontier Warbow',category:'weapon',slot:'mainHand',rarity:'Uncommon',value:65,description:'A reinforced bow for deliberate shots.',purpose:'Dexterity, 1d8 piercing. Two-handed ranged weapon; +1 to hit.',weapon:{damage:'1d8',damageType:'piercing',ability:'dex',properties:['ranged','twoHanded']},attackBonus:1},
  {id:'ward-staff',name:'Wardbinder Staff',category:'focus',slot:'mainHand',rarity:'Uncommon',value:65,description:'Its bronze rings hum when a spell holds steady.',purpose:'Equip: +2 spell attack bonus, +1 spell save DC. Occupies your main hand.',spellAttackBonus:2,spellDcBonus:1},
  {id:'field-plate',name:'Field Plate',category:'armor',slot:'armor',rarity:'Rare',value:130,description:'Articulated plate repaired by an outpost smith.',purpose:'Base AC 17, no Dexterity bonus. Heavy and conspicuous: −2 Stealth. Any class may wear it in this custom ruleset.',armor:{base:17,dexCap:0},skillBonuses:{stealth:-2}},
  {id:'duelist-buckler',name:'Duelist’s Buckler',category:'shield',slot:'offHand',rarity:'Uncommon',value:45,description:'A light buckler for turning blows into openings.',purpose:'+1 AC (less than a steel shield), but +1 weapon attack bonus. Cannot be used with a two-handed weapon.',acBonus:1,attackBonus:1},
  {id:'ward-coating',name:'Ward Oil',category:'consumable',rarity:'Uncommon',value:24,description:'One application makes a blade resonate against bound spirits.',purpose:'Apply outside combat to a party member. Their next three successful weapon hits deal +1d4 radiant damage; persists across battles until used.',usable:{contexts:['story'],effect:'coating',target:'ally',cost:'action'}},
  {id:'scholars-lens',name:'Scholar’s Lens',category:'accessory',slot:'accessory',rarity:'Rare',value:80,description:'A glass lens mounted in a ring of etched silver.',purpose:'Equip: +2 Arcana and Investigation; −1 AC. Helps deciphering at the cost of protection.',skillBonuses:{arcana:2,investigation:2},acBonus:-1},
  {id:'resonant-blade',name:'Resonant Blade',category:'weapon',slot:'mainHand',rarity:'Rare',value:120,description:'An unusual blade traded for stories of broken wards.',purpose:'Finesse, 1d8 radiant damage. Bypasses physical resistance, but no extra attack bonus.',weapon:{damage:'1d8',damageType:'radiant',ability:'finesse',properties:['finesse']}}
];
for(const item of newItems)ITEMS[item.id]=item;
// One capped quality upgrade per equipment item. Deterministic variants avoid
// untracked ad-hoc modifiers and make saves comparable and auditable.
const UPGRADE_BASES=Object.values(ITEMS).filter(i=>['weapon','armor','shield','focus'].includes(i.category));
for(const base of UPGRADE_BASES){
  const item=deepClone(base);item.id=`${base.id}-fine`;item.name=`Fine ${base.name}`;item.baseId=base.id;item.upgradeTier=1;
  item.value=base.value+50;item.rarity='Uncommon';
  let effect='';
  if(item.weapon){item.attackBonus=(item.attackBonus||0)+1;item.damageBonus=(item.damageBonus||0)+1;effect='+1 to hit and damage.';}
  if(item.armor){item.armor.base+=1;effect='+1 base AC.';}
  if(item.category==='shield'){item.acBonus=(item.acBonus||0)+1;effect='+1 AC.';}
  if(item.category==='focus'){item.spellAttackBonus=(item.spellAttackBonus||0)+1;effect='+1 spell attack bonus.';}
  item.purpose=`${base.purpose} Fine quality: ${effect} This is the maximum forge tier in this campaign.`;
  ITEMS[item.id]=item;
}
const TOWNS={
  briarwatch:{id:'briarwatch',name:'Briarwatch',subtitle:'The Bell & Bramble',description:'Rain taps the inn’s copper awning. Smith Dera keeps a place for your party beside the forge, and Reeve Aveline pins reports from the wider roads to a public board.',faction:'wardens',services:['inn','forge','supplies','guild','tavern','shrine','workshop','storage'],stock:['healing-potion','antitoxin','healers-kit','holy-water','smoke-bomb','silk-rope','climbing-kit','lantern','herb-bundle','iron-longsword','shortbow','chain-shirt','studded-leather','steel-shield','ash-wand'],rumor:'The missing caravans did not simply vanish. A western tollhouse has been ringing the wrong road signal.'},
  ashford:{id:'ashford',name:'Ashford Crossing',subtitle:'The Three Roads Market',description:'River barges unload beneath a bridge crowded with petitioners. Quartermaster Iona offers contracts, while merchants argue over who should pay to repair the region’s wards.',faction:'trade',services:['inn','forge','supplies','guild','tavern','shrine','workshop','storage'],stock:['healing-potion','greater-healing','antitoxin','healers-kit','holy-water','smoke-bomb','herb-bundle','ward-fragment','climbing-kit','storm-grounder','ward-coating','dueling-blade','greatsword','warbow','ward-staff','duelist-buckler','wayfarer-boots'],rumor:'Sabotage at the western span and poison in the marsh share the same copper dust. Someone is moving ward machinery downstream.'},
  highpass:{id:'highpass',name:'Highpass Watch',subtitle:'The Last Warm Hearth',description:'The outpost’s lamps swing in the mountain wind. Captain Sorrel has room for refugees but not another failed expedition. Beyond the parapet, stormlight threads the old signal towers.',faction:'wilds',services:['inn','forge','supplies','guild','tavern','shrine','workshop','storage'],stock:['healing-potion','greater-healing','antitoxin','healers-kit','holy-water','smoke-bomb','herb-bundle','ward-fragment','storm-grounder','climbing-kit','ward-coating','field-plate','sentinel-charm','scholars-lens','resonant-blade','warbow','ward-staff'],rumor:'The final beacon does not need a new master. The old wardens designed it to answer a council of voices, not a single command.'}
};
const MERCHANTS={
  caravan:{id:'caravan',name:'Pella’s Road Caravan',role:'Field trader',personality:'Pella counts every flask twice and remembers anyone who returns an empty bottle.',stock:['healing-potion','healers-kit','smoke-bomb','silk-rope','herb-bundle'],offer:'Escort the wagon through the exposed stretch: the party loses a little daylight and 2 HP each, but Pella gives a permanent 5% caravan discount. Once per campaign.'},
  specialist:{id:'specialist',name:'Fen, the Weather Reader',role:'Expedition specialist',personality:'Fen listens to the ground before setting out a carefully limited kit of supplies.',stock:['antitoxin','climbing-kit','storm-grounder','lantern','ward-coating','greater-healing'],offer:'Fen sells regional tools, never a guaranteed solution to an undiscovered puzzle.'},
  relic:{id:'relic',name:'Edda’s Cabinet of Unlikely Things',role:'Relic broker',personality:'Edda will exchange a rare trinket for a stable ward fragment and a little honest coin.',stock:['resonant-blade','scholars-lens','wayfarer-boots','sentinel-charm'],offer:'Exchange one ward crystal fragment and 30 gold for a Wayfarer’s Boots pair. One exchange per meeting.'}
};
const RECIPES=[
  {id:'brew',name:'Brew Greater Healing',itemId:'greater-healing',ingredients:[{itemId:'herb-bundle',quantity:2}],gold:8,description:'Two Medicinal Herbs + 8 gold → one Greater Healing Draught.'},
  {id:'charm',name:'Assemble Sentinel Charm',itemId:'sentinel-charm',ingredients:[{itemId:'ward-fragment',quantity:1}],gold:30,description:'One Ward Crystal Fragment + 30 gold → one Sentinel Charm.'}
];
const PERSONAL={
  orin:{id:'orin',quest:'bridge',name:'The People Behind the Shield',prompt:'Orin recognizes a refugee’s old company badge. “We left civilians behind once. Not again. Help me secure a route for them before we charge the gate.”',goal:'Resolve the Ashford bridge crisis after talking to Orin. The rescue can succeed by force or a negotiated crossing.',reward:'At level 7, Shield-and-Strike becomes available: protect the whole party and grant Orin an immediate attack.'},
  maren:{id:'maren',quest:'archive',name:'Names Worth Remembering',prompt:'Maren carries a list of vanished shrine keepers. “The archive may have their last letters. Even if we cannot save them, their families deserve the truth.”',goal:'Resolve the drowned archive after talking to Maren; bring its findings to the living.',reward:'At level 7, Shared Resolve becomes available: Maren and the hero heal together and clear a harmful condition.'},
  nessa:{id:'nessa',quest:'signal',name:'A Signal for Home',prompt:'Nessa knows the signal tower’s keeper. “She taught me to leave a light for the lost. Let’s make sure her last signal reaches someone.”',goal:'Resolve the Highpass signal tower after talking to Nessa.',reward:'At level 7, Crossfire becomes available: Nessa fires an immediate attack and exposes the target.'}
};

// Each expedition has its own evidence, approaches, moral stakes and aftermath.
// Numerical rewards are objective-based: social and combat solutions pay the same XP.
const QUESTS={
  road:{id:'road',name:'The Toll of Empty Wagons',level:2,town:'briarwatch',unlock:'bell',nextTown:'ashford',xp:850,gold:75,region:'The western road',threat:'Armed extortion and a trapped causeway. A rope or climbing kit can open a side approach.',faction:'trade',
    brief:'Three wagons carrying winter seed have stopped answering their road signals. Find the missing drivers before the village’s planting stores are sold across the border.',
    opening:'An abandoned wagon stands with its wheels chocked, not broken. From the tollhouse beyond, a bell repeats three short notes. A driver behind a shutter flashes a hand and vanishes.',
    clue:'The road signal has been reversed. Drivers are being held while their cargo is inventoried; the toll captain’s own payment slips contradict his orders.',
    investigate:{label:'Compare the wagon manifest with the toll notices',skill:'investigation',alt:['insight'],success:'You find two incompatible seals. The captain has been collecting an illegal second toll and hiding the drivers who objected.',failure:'The handwriting defeats you, but you find a driver’s scratched tally: the prisoners are still alive. You now know where to focus.'},
    route:{label:'Cross under the causeway and reach the drivers',skill:'athletics',alt:['stealth'],tools:['silk-rope','climbing-kit'],success:'You cross beneath the sentries. The prisoners pass you a complete set of duplicate receipts.',failure:'A loose stone gives you away. You reach the tollhouse, but the captain pulls his guards inward.'},
    crisis:'Captain Venn offers to release the wagons if you leave the documents. The drivers watch his hands; one rests on a signal cord leading toward their locked yard.',
    peaceful:{label:'Use the duplicate receipts to make the guards stand down',skill:'persuasion',alt:['intimidation'],success:'The guards read what they have been paid to enforce. One cuts the yard lock; the captain surrenders his keys without a fight.',failure:'Venn calls the receipts stolen and signals the yard guard. His hesitation gives you a chance to reach the lock before the drivers are moved.'},
    objective:{name:'Release the wagon drivers',label:'Break the yard lock',description:'Two successful actions release the drivers and end the encounter without needing to defeat every guard.',skill:'sleightOfHand',alt:['athletics'],target:2,deadline:5,failText:'Venn moves part of the stolen cargo. The seed shortage will persist, and the drivers still need a way out.',successText:'The drivers escape with their wagons; the remaining guards abandon the tollhouse.'},
    foe:'toll-captain',foeName:'Captain Venn',enemyTheme:'road',
    after:'The drivers recover their animals. The confiscated coin could compensate the households at once or fund an escort for future caravans.',
    decisions:[{id:'households',label:'Return the illegal tolls to the drivers',text:'Families recover their winter coin. Briarwatch’s trust in you grows.',rep:{wardens:2},flag:'road_restitution'},{id:'escort',label:'Fund a permanent caravan escort',text:'Iona receives enough money to keep a watch on the road. Trading houses recognize your work.',rep:{trade:2},flag:'road_escort'}]
  },
  marsh:{id:'marsh',name:'Bitter Water at Fenmere',level:3,town:'ashford',unlock:'road',xp:1250,gold:100,region:'Fenmere marsh',threat:'Poisonous vapor and flooded paths. Antitoxin protects the next poison save; a lantern helps identify safe valves.',faction:'wilds',
    brief:'Fenmere’s well has turned bitter. The village blames marsh gatherers, who in turn blame a new pumping station. Find the cause before fear becomes violence.',
    opening:'Reeds lie flat around the pumping station. A sick heron watches from a dry pipe. On opposite banks, villagers and gatherers wait with improvised weapons.',
    clue:'The pump carries dissolved ward ash upstream. Both communities drink the same tainted water; neither poisoned the other.',
    investigate:{label:'Examine the pump residue with the gathered healers',skill:'medicine',alt:['nature','investigation'],tools:['lantern'],success:'The copper-green residue is artificial. You trace it to a cracked containment jar feeding the intake.',failure:'Your samples are spoiled, but the sick fish cluster below the new pump. It is enough to turn suspicion toward the machinery.'},
    route:{label:'Reach the intake through the vapor trench',skill:'survival',alt:['nature'],tools:['lantern'],poison:true,success:'You choose the dry stepping stones and arrive without disturbing the trapped vapor.',failure:'A gas pocket ruptures around the party. You reach the intake coughing, with less time to work.'},
    crisis:'A bound marsh guardian lashes at anyone near the valves. Its keeper shouts that opening the spillway will flood the gatherers’ shelters; leaving it shut will poison the well again.',
    peaceful:{label:'Show both banks the residue and organize a controlled release',skill:'persuasion',alt:['medicine'],success:'Both groups carry their vulnerable neighbors to high ground. With no one left in its threatened boundary, the guardian accepts the keeper’s recall.',failure:'The warning gets some people moving, but the keeper cannot calm the guardian. You must open the safe valves while it rages.'},
    objective:{name:'Vent the poisoned intake',label:'Turn a safe intake valve',description:'Three successful actions purge the poison and release the guardian. Antitoxin protects against the trench, not physical attacks.',skill:'nature',alt:['athletics','arcana'],target:3,deadline:6,failText:'The emergency spill floods some shelters. Stop the danger to prevent further losses; the flooded homes will need repair.',successText:'Clean water replaces the bitter flow; the guardian’s bindings dissolve.'},foe:'marsh-guardian',foeName:'Ashbound Marsh Guardian',enemyTheme:'wild',
    after:'With clean water running, the two banks must decide who will care for the pump. Neither trusts the other yet.',
    decisions:[{id:'council',label:'Establish a shared water council',text:'Each bank appoints a keeper. It is slower work, but neither controls the other’s drinking water.',rep:{wilds:2,wardens:1},flag:'marsh_council'},{id:'engineers',label:'Ask Ashford’s engineers to maintain the pump',text:'Paid engineers take charge and guarantee a regular inspection schedule.',rep:{trade:2},flag:'marsh_engineers'}]
  },
  bridge:{id:'bridge',name:'The Last Cart over Ashford',level:4,town:'ashford',unlock:'marsh',xp:1700,gold:125,region:'Ashford’s western span',threat:'Sabotaged anchors and barricades. Climbing gear helps cross; protecting refugees matters more than chasing every raider.',faction:'wardens',
    brief:'Refugees are trapped beyond the western bridge. Orin recognizes the banners of the company holding it. Get the last carts across before a demolition charge is lit.',
    opening:'A bridge bell sounds once for each cart allowed through. The queue stopped an hour ago. Under the span, freshly cut cables sway over the river.',
    clue:'The demolition order is forged. A faction within the bridge company intends to abandon both refugees and its own rear guard.',
    investigate:{label:'Ask the bridge veterans to compare their orders',skill:'insight',alt:['persuasion','history'],success:'Orin points out a commander’s signature from a man who died years ago. Several soldiers realize they were meant to be expendable.',failure:'The veterans close ranks. One quietly warns you that the demolition fuse is already laid beneath the guardhouse.'},
    route:{label:'Cross the maintenance anchors to the far gate',skill:'athletics',alt:['acrobatics'],tools:['climbing-kit','silk-rope'],success:'You reach the fuse box unseen and disconnect the first charge.',failure:'An anchor tears loose. You reach the far bank bruised, while the sentries call their lieutenant.'},
    crisis:'Lieutenant Hal says her orders allow no exceptions. Behind her, a child in the last cart asks Orin whether soldiers always leave first.',
    peaceful:{label:'Offer the soldiers a shared withdrawal with the refugees',skill:'persuasion',alt:['intimidation'],success:'Hal orders every cart onto the bridge, then marches her company out behind them. No one is left as a diversion.',failure:'Most soldiers hesitate, but the demolition crew follows its own orders. You must clear the cart route under fire.'},
    objective:{name:'Escort the final refugee carts',label:'Open a lane for a refugee cart',description:'Three successful actions secure the evacuation. Companions hold the demolition crew away from you.',skill:'athletics',alt:['persuasion','survival'],target:3,deadline:6,failText:'One loaded supply cart is lost to the river. The remaining people still need a crossing, and Highpass will receive fewer blankets and tools.',successText:'The last cart reaches the near bank; the demolition crew has nothing left to hold hostage.'},foe:'bridge-lieutenant',foeName:'Demolition Lieutenant',enemyTheme:'soldier',
    after:'The bridge is safe for now. Hal asks whether you will make an example of the confused soldiers or let them help repair what they nearly destroyed.',
    decisions:[{id:'repair',label:'Offer supervised repair work instead of punishment',text:'The company works beside the refugees. Orin recognizes a way to make his old failure count for something.',rep:{wardens:2,wilds:1},flag:'bridge_amnesty'},{id:'tribunal',label:'Preserve the orders and call a public tribunal',text:'The forged orders enter the public record. Ashford’s council must answer for the chain of command.',rep:{trade:2,wardens:1},flag:'bridge_tribunal'}]
  },
  archive:{id:'archive',name:'Letters from the Drowned Archive',level:5,town:'ashford',unlock:'bridge',nextTown:'highpass',xp:2200,gold:155,region:'The drowned archive',threat:'Rising water, undead wardens and fragile records. A lantern helps navigation; holy water or radiant weapons affect the undead.',faction:'wardens',
    brief:'Maren’s missing shrine keepers sent their last letters here. Find the archive’s ward diagram and recover what remains before the reservoir rises again.',
    opening:'Desks drift at the foot of a flooded stair. Above them, a spectral archivist keeps sorting ruined pages into dry drawers that no longer exist.',
    clue:'The ward network was built as a council of independent voices. A single central command would bind every keeper as Sable tried to bind the bell spirit.',
    investigate:{label:'Read the surviving correspondence with Maren',skill:'religion',alt:['history','investigation'],tools:['lantern'],success:'Maren reads the names aloud. The letters reveal both the network’s design and the location of its missing keystone.',failure:'Most ink is gone, but Maren identifies the final dispatch mark: all roads in the correspondence lead to Highpass.'},
    route:{label:'Navigate the flooded stacks without breaking the seals',skill:'investigation',alt:['survival'],tools:['lantern','silk-rope'],success:'You find a service stair and preserve the dry alcoves along the route.',failure:'A shelf collapses beneath you. You reach the central record chamber with water rising behind your boots.'},
    crisis:'The archivist will not release the ward diagram until every keeper has been accounted for. Some never returned. Destroying it would be easier than admitting the truth.',
    peaceful:{label:'Read the keepers’ names and acknowledge the unfinished record',skill:'religion',alt:['performance','persuasion'],success:'The archivist stops sorting. It asks Maren to deliver the letters, then opens the diagram cabinet and lets the party pass.',failure:'The unfinished names catch in the ward. The archivist turns hostile, but the cabinet remains close enough to reach.'},
    objective:{name:'Recover the diagram and last letters',label:'Preserve a sealed record drawer',description:'Three successful actions recover the essential records and end the binding. Killing enemies is not required.',skill:'investigation',alt:['religion','sleightOfHand'],target:3,deadline:6,failText:'Some personal letters dissolve before they can be sealed. The diagram and remaining names still need to be recovered.',successText:'The sealed drawers float free; the archivist is released from its impossible duty.'},foe:'archive-keeper',foeName:'The Unfinished Archivist',enemyTheme:'undead',
    after:'The diagram could be published for everyone who tends a ward, or kept under council protection while the sabotage is investigated.',
    decisions:[{id:'publish',label:'Share the diagram with local ward keepers',text:'Knowledge spreads beyond a single council. The keepers can prepare their own defenses.',rep:{wilds:2,wardens:1},flag:'archive_open'},{id:'secure',label:'Give the original to a guarded public archive',text:'The council establishes a protected record, with named witnesses for every copy.',rep:{trade:1,wardens:2},flag:'archive_guarded'}]
  },
  signal:{id:'signal',name:'A Light above the Storm',level:6,town:'highpass',unlock:'archive',xp:2700,gold:180,region:'Highpass signal tower',threat:'Charged ward machinery and exposed climbing. A Storm Grounder opens a protected approach; a climbing kit aids the ascent.',faction:'wilds',
    brief:'The tower above Highpass repeats a distress signal in Nessa’s old code. Restore its beacon before the mountain caravans enter the storm blind.',
    opening:'Lightning crawls sideways across the tower’s bronze rings. Someone has tied a scout’s scarf around the lowest signal arm, where it cannot be seen from the road.',
    clue:'The tower is broadcasting a warning, not summoning the storm. Its keeper diverted the lightning to prevent a central command from taking control.',
    investigate:{label:'Decode the interrupted signal sequence',skill:'perception',alt:['arcana','investigation'],success:'Nessa recognizes her mentor’s shorthand. The last message names the keystone’s carrier and an unguarded path to the summit.',failure:'The sequence is broken, but you identify the distress cadence. Someone tried to keep the tower independent.'},
    route:{label:'Climb beneath the charged signal rings',skill:'athletics',alt:['arcana','acrobatics'],tools:['storm-grounder','climbing-kit'],success:'You earth the nearest ring and reach the control platform through a quiet pocket in the storm.',failure:'The rings arc across your route. You reach the platform, but the tower’s bound sentinels awaken.'},
    crisis:'The keeper lies under a fallen signal arm, still shielding the manual release. A storm sentinel orders you to surrender the beacon to the central ward command.',
    peaceful:{label:'Transmit the keeper’s independent recall sequence',skill:'arcana',alt:['performance','survival'],success:'The sentinel accepts the local keeper’s authority. It braces the arm while you pull the keeper clear and restore the beacon.',failure:'The sentinel recognizes only part of the code. It hesitates long enough for you to reach the manual releases.'},
    objective:{name:'Restore the beacon and free the keeper',label:'Reset a beacon release',description:'Three successful actions end the encounter. The Storm Grounder also helps these objective checks.',skill:'arcana',alt:['athletics','sleightOfHand'],target:3,deadline:6,failText:'The beacon loses its long-range lens. The keeper still needs release, and some caravans will have to wait for daylight.',successText:'The beacon turns toward the road; the keeper’s warning reaches Highpass.'},foe:'storm-sentinel',foeName:'Stormbound Sentinel',enemyTheme:'storm',
    after:'Nessa receives her mentor’s last reliable map. Highpass asks which travelers should receive the first safe signal windows.',
    decisions:[{id:'refugees',label:'Prioritize the refugee and healer caravans',text:'The most vulnerable travelers reach shelter first. The outpost’s trust grows.',rep:{wilds:2,wardens:1},flag:'signal_refugees'},{id:'supply',label:'Prioritize supply trains for the whole pass',text:'Food and repair equipment arrive before the next storm front.',rep:{trade:2,wilds:1},flag:'signal_supply'}]
  },
  summit:{id:'summit',name:'The Price of a Keystone',level:7,town:'highpass',unlock:'signal',xp:3200,gold:215,region:'Glasswind summit',threat:'Rival claimants, fragile bridges and exposed negotiations. Climbing gear helps travel; information and reputation may prevent a fight.',faction:'trade',
    brief:'A courier carries the ward keystone toward Glasswind. Three factions have promised to protect the region if you hand it to them. Find the courier and decide who can be trusted with power.',
    opening:'Three camps share a ledge too narrow for a battle. The courier sits between them, protecting a wrapped object while representatives argue over whose banner it belongs beneath.',
    clue:'Each claimant has omitted a condition from its offer. The courier’s oath permits a shared custody agreement witnessed by independent ward keepers.',
    investigate:{label:'Compare all three custody agreements',skill:'insight',alt:['investigation','history'],success:'You expose the missing clauses without humiliating their authors. A common agreement becomes possible.',failure:'The promises blur together, but the courier points to the part none of them read aloud: custody can be shared.'},
    route:{label:'Secure a neutral meeting place beyond the cracked bridge',skill:'survival',alt:['athletics','persuasion'],tools:['climbing-kit','silk-rope'],success:'You establish a safe crossing and invite one witness from each camp.',failure:'A support cracks during the crossing. No one is lost, but accusations fly and hired guards draw weapons.'},
    crisis:'An agent of the central command offers to end the argument by binding the keystone to one keeper. The courier refuses, and the agent reaches for the wrapped stone.',
    peaceful:{label:'Bind the claimants to a witnessed shared-custody oath',skill:'persuasion',alt:['insight','religion'],success:'Each representative signs in front of their own people. The agent loses the authority it used to demand obedience.',failure:'Two representatives agree; the third panics as the agent seizes a witness. You must break the coercive seals before anyone is bound.'},
    objective:{name:'Break the coercive custody seals',label:'Release a witness from a binding seal',description:'Three successful actions free the witnesses and secure the keystone. Companions cannot negotiate these releases for the hero.',skill:'persuasion',alt:['arcana','athletics'],target:3,deadline:6,failText:'One representative loses trust during the delay. The keystone still needs securing; any custody agreement will begin under strain.',successText:'The witnesses stand together and the agent’s seals fall apart.'},foe:'command-agent',foeName:'Agent of the Single Voice',enemyTheme:'caster',
    after:'The keystone is yours to carry, but not necessarily yours to own. Its custody will shape who answers the final beacon.',
    decisions:[{id:'shared',label:'Keep custody shared among the local wards',text:'The local keepers trust you to carry the keystone without claiming it.',rep:{wilds:2,wardens:2},flag:'keystone_shared'},{id:'council',label:'Place custody with an accountable regional council',text:'The council names witnesses and accepts public responsibility for the stone.',rep:{trade:2,wardens:1},flag:'keystone_council'}]
  },
  breach:{id:'breach',name:'The Quiet District',level:8,town:'highpass',unlock:'summit',xp:3800,gold:245,region:'The abandoned ward district',threat:'Sleep-binding constructs and sealed evacuation gates. Ward oil and tools help, but choosing an evacuation route matters most.',faction:'wardens',
    brief:'An entire district has stopped sending messengers. Its residents still move through familiar routines, but none can choose to leave. Break the command relays without turning the streets into a battlefield.',
    opening:'A baker kneads the same empty board. A child opens and closes a school gate. Every movement pauses when the bell in the central square clicks rather than rings.',
    clue:'The relays use remembered routines to replace decisions. Interrupting their shared rhythm will release the residents without damaging the wards that keep them safe.',
    investigate:{label:'Find the break between remembered routine and living choice',skill:'insight',alt:['arcana','medicine'],success:'You ask a resident a question with no familiar answer. For a moment they wake and point out the three relay anchors.',failure:'Your questions fail to wake anyone, but Maren notices that their pauses do not align with the street clock. The command is external.'},
    route:{label:'Reach the relays through the service courtyards',skill:'stealth',alt:['investigation','survival'],tools:['thieves-tools','lantern'],success:'The routines conceal your movement. You wedge the evacuation gate before the relay notices.',failure:'A service door rings against a guard’s route. Sentinels arrive, but the evacuation gate is within reach.'},
    crisis:'The district’s bound magistrate begs you not to destroy the protective wards. The command construct uses her voice to order the sentinels to keep everyone safely inside.',
    peaceful:{label:'Give the residents a new, voluntary signal to follow',skill:'performance',alt:['persuasion','religion'],success:'An unfamiliar song moves from window to window. The residents choose to answer it; the command loses its borrowed voices.',failure:'A few residents wake, enough to begin an evacuation. The construct tightens its remaining hold and sends the sentinels after you.'},
    objective:{name:'Disconnect the command without destroying the wards',label:'Free a command relay',description:'Four successful actions release the district. Complete the objective before round seven to preserve all three local wards.',skill:'arcana',alt:['sleightOfHand','religion'],target:4,deadline:7,failText:'The emergency mechanism burns out one local ward. The residents still need release, and later repairs will be unavoidable.',successText:'The last relay goes quiet. People begin making small, uncertain choices of their own.'},foe:'relay-construct',foeName:'The Borrowed Magistrate',enemyTheme:'construct',
    after:'The magistrate asks who should decide when a ward may override a person’s wishes. The answer will travel with you to the final beacon.',
    decisions:[{id:'consent',label:'Require the keeper’s and community’s consent',text:'The district adopts a double-consent rule. Independence now has a practical safeguard.',rep:{wilds:2,wardens:2},flag:'district_consent'},{id:'oversight',label:'Create a public emergency oversight council',text:'Emergency powers require named, reviewable votes and a fixed expiry.',rep:{trade:2,wardens:1},flag:'district_oversight'}]
  },
  beacon:{id:'beacon',name:'The Chorus at Dawn',level:9,town:'highpass',unlock:'breach',xp:4400,gold:300,region:'The first ward beacon',threat:'A command engine protected by bound echoes. The keystone, your allies, and the decisions recorded on the road determine how it can be stopped.',faction:'wardens',
    brief:'The central command is preparing its final signal. Carry the keystone to the first beacon and decide whether the ward network will become a shield shared by many or a command held by one.',
    opening:'The first beacon stands above the cloud line. Voices from the towns you visited echo through its open rings, each clipped into a single obedient note.',
    clue:'The command has no voice of its own. It can be severed by making the wards answer independently, or destroyed at the cost of burning the central lens.',
    investigate:{label:'Listen for the separate voices beneath the command',skill:'perception',alt:['religion','arcana'],success:'You recognize the people behind the notes. Their choices along the road give you a sequence the command cannot predict.',failure:'The chorus overwhelms you, but your companions each find one familiar voice. You can still reach the keystone cradle.'},
    route:{label:'Carry the keystone through the resonant rings',skill:'arcana',alt:['athletics','survival'],tools:['storm-grounder'],success:'You ground the nearest rings and reach the cradle before the command finishes tuning them.',failure:'A peal throws the party against the stone. The cradle remains reachable, but the bound echoes gather around it.'},
    crisis:'The Single Voice offers perfect safety at the cost of every keeper’s choice. The promise sounds less convincing now that you have seen whom such safety leaves behind.',
    peaceful:{label:'Ask the independent keepers to answer together',skill:'persuasion',alt:['performance','religion'],success:'The keepers answer in different rhythms. The command cannot make them agree without choosing for them; its central note falls apart.',failure:'The first voices answer, then falter under the pressure. Your companions hold the echoes back while you open the remaining channels.'},
    objective:{name:'Restore a chorus of independent wards',label:'Open an independent ward channel',description:'Four successful actions sever the command. Your earlier community decisions lower the difficulty; the change is shown before rolling.',skill:'arcana',alt:['persuasion','religion'],target:4,deadline:7,failText:'The central lens cracks while the command continues. Break the command to free the roads; rebuilding the lens will take longer.',successText:'Separate voices fill the rings. The region’s wards become a chorus, not a chain.'},foe:'single-voice',foeName:'The Single Voice',enemyTheme:'boss',
    after:'Dawn reaches the roads below. Your party has earned the right to define what its strength is for. The guild has prepared the first advancement trial—not as a reward for obedience, but as a question.',
    decisions:[{id:'distributed',label:'Leave the wards in independent, cooperating hands',text:'Every settlement keeps its own voice. Your party becomes a link between them, not a ruler above them.',rep:{wilds:3,wardens:2},flag:'ending_distributed'},{id:'charter',label:'Found a public charter for the ward network',text:'A shared charter limits the network’s power and names the people who must answer for its use.',rep:{trade:3,wardens:2},flag:'ending_charter'}]
  },
  trial:{id:'trial',name:'Oath of the Road — First Advancement',level:10,town:'highpass',unlock:'beacon',xp:0,gold:0,region:'The guild’s echo court',threat:'A supervised trial of judgment and technique. Failure has no gold penalty and can be retried; your specialization cannot be lost to one bad roll.',faction:'wardens',
    brief:'Show how you use your strength when victory and protection compete. Complete this trial to choose your level-10 specialization.',
    opening:'The trainers create an echo of the road you have traveled. Your companions stand beside you; behind a fragile gate, voices ask whether your next step will leave them behind.',
    clue:'The trial’s gate responds to commitment, not brute force. A deliberate choice of responsibility can resolve the echo without defeating it.',
    investigate:{label:'Discuss what the road taught you with your companions',skill:'insight',alt:['history','religion'],success:'Each companion names a decision they remember. Together you identify the moment the trial is asking you to change.',failure:'You disagree about the past, but the disagreement clarifies the question. There is no single approved answer.'},
    route:{label:'Demonstrate your class technique on the approach',skill:'athletics',alt:['arcana','stealth','performance','medicine','survival'],success:'The trainers recognize a practiced technique used for a purpose. The gate responds.',failure:'The technique falters, and a trainer resets the echo. You learn from the miss and proceed without losing your path.'},
    crisis:'The echo offers an easy victory while the gate behind it cracks. The trainers watch whether you pursue the enemy or take responsibility for the people in your care.',
    peaceful:{label:'Name your responsibility and let the easy victory go',skill:'insight',alt:['persuasion'],success:'You refuse the false choice. The echo bows and the gate opens; the trial recognizes your judgment.',failure:'The words are not enough. The trainers ask you to show the decision while the echo presses its attack.'},
    objective:{name:'Demonstrate responsibility under pressure',label:'Secure the trial gate',description:'Three successful actions complete the demonstration. A failed trial is recoverable and cannot permanently lock an advancement.',skill:'athletics',alt:['arcana','medicine','stealth','performance','survival'],target:3,deadline:7,failText:'The trainers mark the missed deadline for discussion. Finish the demonstration or withdraw and retry; your advancement cannot be permanently lost.',successText:'The gate holds. The trainers acknowledge the intent behind your technique.'},foe:'oath-echo',foeName:'Echo of the Unchosen Road',enemyTheme:'trial',
    after:'You have reached the first threshold. Choose a specialization in the Progression panel; its defining ability will be available immediately. A relief-convoy expedition lets you use it on the road; the practice arena remains available for safe experiments.',
    decisions:[{id:'accept',label:'Complete the trial and choose your path',text:'The guild records your first advancement trial. No trainer chooses your specialization for you.',rep:{wardens:1},flag:'trial_earned'}]
  }
};

// A real post-advancement mission means the level-10 reward is not a dead-end button.
QUESTS.aftermath={id:'aftermath',name:'The Road You Keep',level:10,town:'highpass',unlock:'trial',requiresAdvancement:true,xp:0,gold:240,region:'The returning caravan road',threat:'An isolated command engine is holding a relief caravan. Ward Oil can affect its guards; a climbing kit offers access to the emergency channel.',faction:'trade',
  brief:'Take your new specialization onto the road. A surviving command engine has mistaken a relief convoy for an invading army; the first free towns need its medicine.',
  opening:'Children have painted the convoy’s crates with the symbols of their towns. Ahead, a gate of pale metal repeats an obsolete evacuation order. The driver has stopped arguing and started counting the sick.',
  clue:'The engine still accepts the old roadwardens’ responsibility oath. Its own emergency channel can release the gate without restoring the network’s central command.',
  investigate:{label:'Read the obsolete evacuation orders with the drivers',skill:'investigation',alt:['insight','history'],success:'The contradictory commands reveal an emergency channel. It was designed for a keeper who would take personal responsibility for admitting the convoy.',failure:'The exact wording is damaged, but the drivers remember a keeper’s oath. You know enough to challenge the command, though not how to make it easy.'},
  route:{label:'Reach the emergency channel above the gate',skill:'athletics',alt:['sleightOfHand','arcana'],tools:['climbing-kit','silk-rope'],success:'The party reaches the channel before the guards can close the gallery. Your new training makes the opening feel usable, not merely lucky.',failure:'A guard breaks the gallery brace. The party reaches the channel with injuries and without surprise.'},
  crisis:'The engine asks who will answer for the people beyond its gate. Its guards advance. You may offer a binding promise, disable the engine, or work the channel while your companions keep the road open.',
  peaceful:{label:'Take responsibility for the convoy under the keepers’ oath',skill:'persuasion',alt:['religion','performance'],success:'The engine accepts a responsible keeper in place of a distant master. It opens the gate and records the convoy’s destination, not its obedience.',failure:'The damaged engine refuses the oath. You must make room for the convoy before its guards enforce the old order.'},
  objective:{name:'Open the relief convoy’s route',label:'Release an emergency road channel',description:'Four successful actions open the gate. Your advancement abilities are available, including objective-focused alternatives for Saboteurs and Lorekeepers.',skill:'athletics',alt:['arcana','persuasion','sleightOfHand','religion'],target:4,deadline:6,failText:'The convoy loses a day’s supply while it waits. Open the road to get the medicine through; the delay will be remembered.',successText:'The convoy passes between lowered weapons. People see what your new title means before anyone announces it.'},
  foe:'last-command',foeName:'The Last Command Engine',enemyTheme:'construct',
  after:'The convoy reaches the first settlement before dusk. Your specialization has faced something more demanding than a title ceremony: people depending on the way you choose to act.',
  decisions:[{id:'keepers',label:'Leave local keepers in charge of the road',text:'The convoy appoints a keeper from each town. Your party leaves a working agreement rather than another command. This season’s adventure is complete.',rep:{trade:3,wilds:2},flag:'epilogue_keepers'},{id:'patrol',label:'Found a voluntary road patrol with the companions',text:'Your companions help volunteers agree on duties they can refuse or revise. The road belongs to those who keep it open. This season’s adventure is complete.',rep:{wardens:3,trade:2},flag:'epilogue_patrol'}]};

function choice(id,label,rest={}){return {id,label,description:rest.description||'',once:true,...rest};}
function clue(id,name,text){CLUES[id]={id,name,text};}
function installQuest(q){
  const prefix=`q-${q.id}`;
  const evidence=`${q.id}-evidence`;
  clue(evidence,`${q.name}: established lead`,q.clue);
  const preparation=`prepared:${q.id}`;
  const approach=`approach:${q.id}`;
  const investigate={skill:q.investigate.skill,alternateSkills:q.investigate.alt,dc:11+Math.floor(q.level/2),tools:q.investigate.tools};
  const routeCheck={skill:q.route.skill,alternateSkills:q.route.alt,dc:12+Math.floor(q.level/2),tools:q.route.tools};
  STORY_NODES[`${prefix}-start`]={id:`${prefix}-start`,act:`Expedition • Level ${q.level}`,title:q.name,location:q.region,objective:q.brief,opening:q.opening,safeRest:true,questId:q.id,phase:'start',choices:[
    choice('investigate',q.investigate.label,{check:investigate,description:'Establish what is happening before committing. Failure still reveals a useful lead.',success:{text:q.investigate.success,clues:[evidence],setFlags:{[preparation]:true}},failure:{text:q.investigate.failure,clues:[evidence],setFlags:{[`partial:${q.id}`]:true}}}),
    choice('advance',q.route.label,{nextNode:`${prefix}-approach`,description:'Proceed toward the crisis. Preparation remains optional.'})
  ]};
  STORY_NODES[`${prefix}-approach`]={id:`${prefix}-approach`,act:`Expedition • Level ${q.level}`,title:'The approach',location:q.region,objective:q.route.label,opening:'The route ahead offers a careful approach or a direct crossing. Choose how to handle the obstacle; supplies and trained skills can change the risk.',safeRest:false,questId:q.id,phase:'approach',choices:[
    choice('careful',q.route.label,{check:routeCheck,description:`${q.route.tools?.length?'The listed equipment can grant advantage. ':''}A failed approach causes injury (and poison only where described), but does not block the story.`,success:{text:q.route.success,setFlags:{[approach]:true},nextNode:`${prefix}-crisis`},failure:{text:q.route.failure,partyDamage:q.id==='trial'?'0':`${1+Math.floor(q.level/5)}d4`,poison:q.route.poison,nextNode:`${prefix}-crisis`}}),
    choice('direct','Take the obvious route and keep the party together',{description:'No check. Arrive openly without an approach advantage.',result:{text:'The party arrives together by the direct route. You have surrendered surprise, not the opportunity to decide what happens next.',nextNode:`${prefix}-crisis`}})
  ]};
  STORY_NODES[`${prefix}-crisis`]={id:`${prefix}-crisis`,act:`Expedition • Level ${q.level}`,title:'The deciding moment',location:q.region,objective:q.objective.name,opening:q.crisis,safeRest:false,questId:q.id,phase:'crisis',choices:[
    choice('resolve',q.peaceful.label,{requires:{cluesAll:[evidence]},check:{skill:q.peaceful.skill,alternateSkills:q.peaceful.alt,dc:14+Math.floor(q.level/2)},description:'Try a complete noncombat resolution. Established preparation lowers the DC; failure starts the objective encounter.',success:{text:q.peaceful.success,setFlags:{[`method:${q.id}`]:'peace'},nextNode:`${prefix}-after`},failure:{text:q.peaceful.failure,combat:`quest:${q.id}`}}),
    choice('objective',`Protect the party while you ${q.objective.label.toLowerCase()}`,{description:q.objective.description,result:{text:'Your companions take their positions. The objective, its difficulty and its consequences are visible during the encounter.',combat:`quest:${q.id}`}}),
    choice('confront','Confront the threat directly',{description:'Start the same encounter without committing to a method. You may attack, pursue the objective, or retreat.',combat:`quest:${q.id}`})
  ]};
  STORY_NODES[`${prefix}-after`]={id:`${prefix}-after`,act:'Consequences',title:'What you leave behind',location:q.region,objective:'Choose what follows your intervention, then return to town.',opening:q.after,safeRest:true,questId:q.id,phase:'after',choices:q.decisions.map(d=>choice(d.id,d.label,{description:'This decision is permanent. The objective reward is the same for every approach.',result:{text:d.text,setFlags:{[d.flag]:true},completeQuest:q.id,reputation:d.rep,nextNode:`town-${q.nextTown||q.town}`}}))};
  const level=q.level;
  const type=q.enemyTheme;
  const mainHp=22+level*6;
  ENEMIES[q.foe]={id:q.foe,name:q.foeName,maxHp:mainHp,ac:12+Math.floor(level/3),level,abilities:{str:14,dex:12,con:14,int:13,wis:13,cha:14},attack:{name:type==='wild'?'Briar Lash':type==='undead'?'Remembered Toll':'Ward Strike',bonus:3+Math.floor(level/2),damage:`${1+Math.floor(level/5)}d6+${2+Math.floor(level/3)}`,damageType:type==='undead'?'necrotic':type==='storm'?'lightning':'slashing'},aiRole:level>=8?'boss':'leader',tags:type==='undead'?['undead']:[],resistances:type==='undead'?['slashing','piercing','bludgeoning']:[],xp:0};
  const minion=`${q.foe}-retainer`;
  ENEMIES[minion]={id:minion,name:type==='undead'?'Bound Record Keeper':type==='wild'?'Ashbound Reedling':'Bound Retainer',maxHp:10+level*4,ac:11+Math.floor(level/3),level,abilities:{str:12,dex:12,con:12,int:9,wis:11,cha:9},attack:{name:'Guarding Strike',bonus:3+Math.floor(level/3),damage:`1d6+${2+Math.floor(level/3)}`,damageType:'bludgeoning'},aiRole:'soldier',tags:type==='undead'?['undead']:[],xp:0};
  ENCOUNTERS[`quest:${q.id}`]={id:`quest:${q.id}`,name:q.name,enemies:[q.foe,minion,minion],storyScale:0.82,standardScale:1,grittyScale:1.18,xp:0,loot:[],intro:q.crisis,questId:q.id,objective:q.objective,victoryNode:`${prefix}-after`,defeatNode:'defeat'};
}
for(const q of Object.values(QUESTS))installQuest(q);
for(const town of Object.values(TOWNS))STORY_NODES[`town-${town.id}`]={id:`town-${town.id}`,act:'Downtime & preparation',title:town.name,location:town.subtitle,objective:'Recover, develop the party, choose an expedition and prepare for known threats.',opening:town.description,safeRest:true,townId:town.id,choices:[]};

// Continue the original story rather than reset the party or fake a level grant.
STORY_NODES.ending.ending=false;
STORY_NODES.ending.act='Chapter I • Consequences';
STORY_NODES.ending.objective='Report to Briarwatch and open the roads beyond the bell.';
STORY_NODES.ending.opening='The immediate threat beneath Briarwatch has ended. The village waits for your account; what you chose will follow the party onto the wider roads.';
STORY_NODES.ending.choices=[choice('report-bell','Report to the town and prepare for the next adventure',{result:{text:'Aveline pays the agreed contract and introduces you to the road wardens. The party keeps its experience, equipment and relationships.',completeQuest:'bell',nextNode:'town-briarwatch'}})];
STORY_NODES['briarwatch-square'].townId='briarwatch';
STORY_NODES['tovin-infirmary'].townId='briarwatch';
STORY_NODES.defeat.choices=[choice('recover','Accept rescue and return to a safe town',{once:false,description:'Lose up to a quarter of your gold, never equipment or XP. The interrupted encounter can be retried. The supervised trial has no gold penalty.',result:{text:'The survivors and local wardens retrieve the party. The setback remains in the journal; the road is not over.',recover:true}})];
// Old ambiguous descriptions and effects: route-specific truth only.
const v=C.STORY_NODES['bell-vault'];
const expose=v.choices.find(c=>c.id==='expose-sable');
expose.success.combat=undefined;expose.success.nextNode='ending';
expose.success.text='The ledger makes Sable’s lie impossible to sustain. His followers cut the binding, disarm him and surrender him to your party. Evidence wins what a blade need not.';
expose.success.setFlags.spiritFreed=true;
// A practice battle gives the actual new specialization a safe place to operate.
ENEMIES['training-echo']={id:'training-echo',name:'Guild Training Echo',maxHp:160,ac:15,level:10,abilities:{str:14,dex:12,con:14,int:12,wis:12,cha:12},attack:{name:'Blunted Echo',bonus:5,damage:'1d6+2',damageType:'bludgeoning'},aiRole:'soldier',xp:0};
ENCOUNTERS.practice={id:'practice',name:'The Echo Court — practice',enemies:['training-echo'],storyScale:1,standardScale:1,grittyScale:1,xp:0,loot:[],intro:'A supervised practice echo rises. No gold, XP or loot is awarded. Your health, resources and supplies are restored exactly after practice.',victoryNode:'town-highpass',defeatNode:'town-highpass',practice:true};
module.exports={TOWNS,MERCHANTS,RECIPES,PERSONAL,QUESTS,UPGRADE_BASES};
